---
title: "Data Standard"
date: today
format: 
  html:
    toc: true
    toc-depth: 3
    code-fold: false
editor: 
  markdown: 
    wrap: 72
---

## What types of data can be contributed? 

The archive accepts datasets from wildlife systems with confirmed or suspected disease presence, including during outbreaks. 

### Minimum recommended data components are:

| Data type | Examples |
|----------|----------|
| **Movement data** <br>(Occasional detection data and radio telemetry are also acceptable) | GPS, accelerometer, GLS, MOTUS, radio telemetry |
| **Diagnostic test data** <br>(Sample availability / dates of testing) | PCR, serology, culture results |
| **Mortality information** *(optional)* | Cause of death, carcass recovery details |
| **Additional sensor data** *(if available)* | Temperature loggers, heart rate |

::: callout-tip
## Note:

Datasets from individuals suspected to be exposed to disease are also welcome, even if infection data are incomplete.
:::

## Data standard for wildlife infectious disease studies 

To ensure that datasets in the MDA are comparable for disease-focused research, all contributed studies must provide the following required metadata fields. These variables represent the minimum data standard for wildlife infectious disease studies and align with the guidelines described in [Schwantes et al. (2025)](https://doi.org/10.1038/s41597-025-05332-x).

::: callout-tip
## For more detils, see:

- [**A minimum data standard for wildlife disease research and surveillance**](https://www.nature.com/articles/s41597-025-05332-x)
- [**Data standard template as csv**](downloadables/movedisease_reference_data_template.csv)
:::

### Required diagnostic metadata fields

::: callout-important
Detection outcome is required for all records and represents the categorical result of a diagnostic test (positive, negative, or inconclusive if the test was unavailable). Quantitative diagnostic outputs such as PCR Ct values and parasite counts may be reported using optional detection measurement fields. When quantitative values are provided, associated units and relevant methodological context should also be included to ensure interpretability and reuse. Datasets without explicit infection results but collected in known outbreak areas are also valuable and welcome (you can fill out some of the columns with “NA”).
:::

::: {.table-responsive}
| Variable | Type | Description | Example | Required? |
|---------|------|-------------|---------|-----------|
| Sample ID | String | A user-generated, unique ID for the sample. | OS BZ19-114 | Required |
| Animal ID | String | A user-generated unique ID for the individual animal from which the sample was collected. | BZ19-114 to indicate animal ID 114 sampled in 2019 in Belize | Required |
| Animal Taxon | String | Animal taxonomy. | *Lynx rufus* | Required |
| First deployment | String | First deployment date. | YYYYMMDD | Required |
| Latest deployment | String | Latest deployment date. | YYYYMMDD | Required |
| Sensor type | String | Sensor type used to tag the animals. | GPS | Required |
| Host ID | String | The Linnaean classification of the animal from which the sample was collected. | *Desmodus rotundus* | Required |
| Pathogen ID | String | The identity of a parasite detected by the diagnostic test. | Alphacoronavirus | Required |
| Sample collection method | String | The technique used to acquire the sample and/or the tissue from which the sample was acquired. | Swab | Required |
| Sample material | String | Organic tissue or fluid being collected (e.g., liver, blood, skin, whole organism). | Blood | Optional |
| Sample collection date | String | The date when the sample was collected. | YYYYMMDD | Required |
| Detection target | String | The taxonomic identity of the pathogen being screened for in the sample. | Coronaviridae | Required |
| Detection method | String | The type of diagnostic test performed to detect the pathogen. | Semi-nested PCR | Required |
| Detection outcome | String | Categorical outcome of the diagnostic test. | Positive / Negative / Inconclusive | Required |
| Detection measurement | Number | A numeric measurement associated with pathogen detection that provides more detail than presence/absence. | 27.4 (e.g., PCR Ct value) | Optional |
| Detection measurement units | String | Units associated with the detection measurement. | Ct | Optional (Required if detection measurement is provided) |
| Detection measurement method details | String | Additional details needed to interpret the quantitative measurement. | qPCR, Ct threshold = 35 | Optional |
| Detection measurement interpretation | String | Guidance on how the quantitative value should be interpreted in context. | Ct &lt; 35 considered positive | Optional |
| Detection limit | Number | The lowest value at which the assay reliably detects the pathogen. | 35 | Optional |
| Detection limit units | String | Units associated with the limit of detection. | Ct | Optional |
:::

::: callout-tip
## Examples:

You can find examples in the [Studies](studies.qmd).
:::